import Head from 'next/head';
import Image from 'next/image';

type linksCard = {
    url: string;
    title: string;
    description: string;
};

export default function Home() {
    const links: linksCard[] = [
        {
            url: 'https://nextjs.org/docs',
            title: 'Documentation',
            description: 'Find in-depth information about Next.js features and API.',
        },
        {
            url: 'https://nextjs.org/learn',
            title: 'Learn',
            description: 'Learn about Next.js in an interactive course with quizzes!',
        },
        {
            url: 'https://github.com/vercel/next.js/tree/master/examples',
            title: 'Examples',
            description: 'Discover and deploy boilerplate example Next.js projects.',
        },
        {
            url: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
            title: 'Deploy',
            description: 'Instantly deploy your Next.js site to a public URL with Vercel.',
        },
    ];

    return (
        <div className="flex flex-col items-center justify-center h-screen min-h-screen px-2 py-0">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center justify-center px-0 py-20">
                <h1 className="leading-5 text-[4rem] text-center mb-10">
                    Welcome to{' '}
                    <a
                        href="https://nextjs.org"
                        className="text-blue-600 hover:underline active:underline focus:underline"
                    >
                        Next.js!
                    </a>
                </h1>

                <p className="text-2xl leading-6 text-center">
                    Get started by editing{' '}
                    <code className="p-3 text-lg bg-gray-100 rounded-md">pages/index.js</code>
                </p>

                <div className="flex flex-col flex-wrap items-center justify-center w-full mt-12 md:flex-row md:max-w-3xl">
                    {links.map((link, index) => (
                        <a
                            key={`${index}-${link}`}
                            href={link.url}
                            className="transition-all ease-linear duration-[0.15s] m-4 p-4 md:p-8 text-left border border-gray-300 rounded-[10px] w-[45%] hover:text-blue-600 hover:border-blue-600 focus:text-blue-600 focus:border-blue-600  active:text-blue-600 active:border-blue-600"
                        >
                            <h2 className="mb-4 text-2xl">{link.title} &rarr;</h2>
                            <p className="text-xl leading-6">{link.description}</p>
                        </a>
                    ))}
                </div>
            </main>

            <footer className="flex items-center justify-center w-full border-t border-gray-300 h-28">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-center flex-grow"
                >
                    Powered by{' '}
                    <span className="h-[1em] ml-2">
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
